name: Log Time Job
on:
  push:
    branches:
      - main  # Trigger on push to main branch
  schedule:
    - cron: "*/1 * * * *"  # Runs every 1 minute
  
jobs:
  log_time:
    runs-on: ubuntu-latest
    # Add permission for GITHUB_TOKEN
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Use token for authentication
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run logging script
        run: |
          chmod +x log_time.sh
          ./log_time.sh
          
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # Configure safe directory for git
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          
          # Add changes
          git add log.txt
          
          # Try to commit and push
          git commit -m "Update log file with new timestamp [skip ci]" || echo "No changes to commit"
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
